### ISSUE TITLE
require mdast-util-position fails with --config-path

### ISSUE THREAD

**Issue by tkruse** [wemake-services/remark-lint-are-links-valid#1]
using nodejs 4.0.0 and:
```
  // package.json
  "dependencies": {
    "remark-cli": "^1.0.0",
    "remark-lint": "^4.0.2",
    "remark-lint-sentence-newline": "^2.0.0",
    "remark-validate-links": "^4.1.0",
    "remark-lint-are-links-valid": "^1.0.2"
  }
```
and .remarkrc:
```
{
"plugins": {
    "remark-lint": {
        "unordered-list-marker-style": "consistent",
        "list-item-bullet-indent": false,
        "list-item-indent": false,
        "list-item-spacing": false,
        "no-html": false,
        "maximum-line-length": false,
        "no-file-name-mixed-case": false,
        "heading-increment": false,
        "no-multiple-toplevel-headings": false,
        "no-consecutive-blank-lines": false,
        "maximum-line-length": 9000,
        "maximum-heading-length": 300,
        "no-heading-punctuation": false,
        "no-duplicate-headings": false,
        "emphasis-marker": "*",
        "no-tabs": false,
        "blockquote-indentation": false,
        "strong-marker": "*",
        "external": ["remark-lint-are-links-valid"]
    }
  },
  "settings": {
    "bullet": "*",
    "listItemIndent": "1",
    "strong": "*",
    "emphasis": "*"
  }
}
```

I get:
```
./node_modules/.bin/remark ../../file.md --no-color -q --rc-path ./remark/.remarkrc  --frail
../../file.md
        1:1  error    Error: Cannot find module 'mdast-util-position'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (.../nodejs/node_modules/remark-lint-are-links-valid/dist/are-links-valid.js:10:13)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

This file exists though:
```
./node_modules/remark-lint-are-links-valid/node_modules/remark-lint/node_modules/mdast-util-position
```
but not 
```
remark-lint-are-links-valid/node_modules/mdast-util-position
```
(I know very little about npm packaging)

**Comment by sobolevn** [comment]
Hmm, looking at you `package.json` file: `remark-lint-are-links-valid` dependency does not seem to be installed.

**Comment by tkruse** [comment]
Sorry, copied the package.json after removing agin. Changed in the original post above. Error still persists

**Comment by sobolevn** [comment]
Sorry, I can't reproduce your error, but I have a few guesses:

1. some issues with your config: see [full example here](https://github.com/sobolevn/awesome-cryptography/blob/master/package.json)
2. your `node.js` is outdated `== 4.0.0` (I will create a `Travis` strategy to test this)

**Comment by tkruse** [comment]
Ah, somehow thought 4.0.0 was the latest. I can also try using a more recent version.

**Comment by tkruse** [comment]
The same happens with 4.4.7

**Comment by tkruse** [comment]
I created a repo to reproduce: https://github.com/tkruse/mvl_bug

The error only seems to occur when using the --config-path option of remark.

**Comment by sobolevn** [comment]
Thanks, will try it soon.

**Comment by sobolevn** [comment]
Hmm, created a minor fixes, including a `travis` strategy for `node@4.4`.

Still can't reproduce it:

```
[12:41:55] sobolev :: MacBook-Pro-Nikita  ➜  ~/Desktop/mvl_bug ‹master› » nvm use 4.4.7 
Now using node v4.4.7 (npm v2.15.8)
[13:05:10] sobolev :: MacBook-Pro-Nikita  ➜  ~/Desktop/mvl_bug ‹master› » npm test                 

> ReproduceBug@0.0.0 test /Users/sobolev/Desktop/mvl_bug
> ./node_modules/remark/bin/remark README.md -f --config-path remark/.remarkrc

# Reproduce mddast are links valid package json bug

bla bla
README.md: no issues found
```

But after some closer look, I found out you are specifying options the wrong way: instead of `./node_modules/remark/bin/remark README.md -f --config-path ./remark/.remarkrc` use `./node_modules/remark/bin/remark --config-path ./remark/.remarkrc README.md -f`

Here's the difference:

```
[13:18:05] sobolev :: MacBook-Pro-Nikita  ➜  ~/Desktop/mvl_bug ‹master*› » ./node_modules/remark/bin/remark --config-path=./remark/.remarkrc README.md
# Reproduce mddast are links valid package json bug

bla bla

Broken [link](http://asdasdasdasdasdsdfdsfdsggsdgs.rc/)
README.md
        5:8  warning  Link is broken: http://asdasdasdasdasdsdfdsfdsggsdgs.rc/  are-links-valid

⚠ 1 warning
```

But still no errors.

**Comment by tkruse** [comment]
I can reproduce on travis:
https://travis-ci.org/tkruse/mvl_bug/builds/150771892

If you have mdast-util-position installed globally on your machine, I guess npm will pick it up form there, maybe?

**Comment by sobolevn** [comment]
Can you please try new version from the `master` branch?

I have removed the `mdast-util-position`: https://github.com/wemake-services/remark-lint-are-links-valid/commit/ad72426cd9727e3c9c59335fd88d73e2cef43d2b#diff-2dfc4fa50f1e780b4fd4280d6e95bf12L10

**Comment by tkruse** [comment]
If you tell me how. I never used any npm package from source.

**Comment by sobolevn** [comment]
http://stackoverflow.com/questions/17509669/how-to-install-nodejs-package-from-github-directly

**Comment by tkruse** [comment]
ok, current master works for my case.

**Comment by sobolevn** [comment]
Cool, I will release a new version shortly.

**Comment by sobolevn** [comment]
`1.0.3` is out!
